### ISSUE TITLE
Calling load(url) doesn't seem to be working.

### ISSUE THREAD

**Issue by jsonnull** [mattdesl/polartone#1]
Calling load(url) for me brings up the song name and artist name, but the visualization freezes where it was and the new song doesn't play. :/

**Comment by mattdesl** [comment]
I should have specified in the console, it only works with SoundCloud URLs. And some of them don't seem to work,  so you may need to try another track. :)

**Comment by jsonnull** [comment]
@mattdesl Yep, it's a soundcloud URL (I'm assuming that's why the artist and song load), but it seems weird that some songs don't seem to work.

Unrelated: would you accept a pull request to allow SoundCloud URLs be appended as a query parameter?

**Comment by notthetup** [comment]
Doh! @jsonnull I just added that. Was about to raise a PR. https://github.com/notthetup/spins

But I'm having issues with the built version. I keep getting the following error. Even without my changes.

`Uncaught Error: camera projection * view is non-invertible`

I guess I should raise a separate issue about it.

**Comment by jsonnull** [comment]
@notthetup I accidentally beat you to it! :P See #2 ...

**Comment by mattdesl** [comment]
> Unrelated: would you accept a pull request to allow SoundCloud URLs be appended as a query parameter?

Updated with this feature, also accepts short form.

eg:
http://mattdesl.github.io/spins/?url=roman-mars/99-invisible-162-mystery-house

**Comment by notthetup** [comment]
:+1:
