### ISSUE TITLE
JavaScript error on fresh clone

### ISSUE THREAD

**Issue by jsonnull** [mattdesl/polartone#2]
When doing a fresh clone, `npm install`, `npm start`:

`camera-base.js:34 Uncaught Error: camera projection * view is non-invertible`

The error is happening at `camera.update()` on line 105 of index.js according to the dev console.

Let me know if you need any more information. I'd love to get this working to try some things.

**Comment by notthetup** [comment]
I guess this is the underlying error that @mattdesl already knows about.

https://github.com/Jam3/perspective-camera/issues/1

**Comment by notthetup** [comment]
A very very very ugly work around I found for now is to use a non-zero value for the 1st element in `opt.position`. I tried using `0.0000000001` and it seems to remove the error.

**Comment by mattdesl** [comment]
Ah, I had fixed this in perspective-camera@2.0 but forgot to bump the package.json dep here.  :smile: Should be fixed now, let me know.
